import {v4 as uuid} from 'uuid'

const name = uuid().slice(0,5)
const email = `${name}@${name}.com`
const password = uuid().slice(0,8)
const url = "http://localhost:3000/"

describe('User Onboarding Test', ()=>{
    it('can navigate to the site', () => {
        cy.visit(url)
        cy.url().should('include', 'localhost')
    })
    it('can get the Name input and type a name in it, check if input value matches input typed', ()=>{
        cy.get('input[name="name"]')
            .type(name)
            .should('have.value', name)
    })
    it('can get the Email input and type an email address in it, check if input value matches input typed', () =>{
        cy.get('input[name="email"]')
            .type(email)
            .should('have.value', email)
    })
    it('can get the Password input and type a password in it, check if input value matches input typed', () =>{
        cy.get('input[name="password"]')
            .type(password)
            .should('have.value', password)
    })
    it('can check the terms of service box', ()=>{
        cy.get('input[name="term"]')
            .check()
            .should('have.checked')
    })
    it('can submit a form', ()=>{
        cy.get('button[name="submit"]')
            .click()
        cy.get('.App')
            .contains(name)
            .contains(email)
            .contains(password)
    })
    it('can show error message for Name', ()=>{
        cy.get('input[name="name"]')
            .type('a')
            .should('have.value','a')
        cy.contains('at least 3')
            .should('exist')
        cy.get('input[name="name"]')
            .type('b')
            .should('have.value','ab')
        cy.contains('at least 3')
            .should('exist')
        cy.get('input[name="name"]')
            .type('c')
            .should('have.value','abc')
        cy.contains('at least 3')
            .should('not.exist')
        cy.get('input[name="name"]')
            .clear()
        cy.contains('Name is required')
            .should('exist')
        cy.get('input[name="name"]')
            .type('abc')
    })
    it('can show error message for Email', ()=>{
        cy.get('input[name="email"]')
            .type('a')
            .should('have.value','a')
        cy.contains('VALID email')
            .should('exist')
        cy.get('input[name="email"]')
            .type('@b')
            .should('have.value','a@b')
        cy.contains('VALID email')
            .should('exist')
        cy.get('input[name="email"]')
            .type('.co')
            .should('have.value','a@b.co')
        cy.contains('VALID email')
            .should('not.exist')
        cy.get('input[name="email"]')
            .clear()
        cy.contains('Email is required')
            .should('exist')
        cy.get('input[name="email"]')
            .type('a@b.co')
    })
    it('can show error message for Password', ()=>{
        cy.get('input[name="password"]')
            .type('a')
            .should('have.value','a')
        cy.contains('at least 8')
            .should('exist')
        cy.get('input[name="password"]')
            .type('bcdefg')
            .should('have.value','abcdefg')
        cy.contains('at least 8')
            .should('exist')
        cy.get('input[name="password"]')
            .type('h')
            .should('have.value','abcdefgh')
        cy.contains('at least 8')
            .should('not.exist')
        cy.get('input[name="password"]')
            .clear()
        cy.contains('Password is required')
            .should('exist')
        cy.get('input[name="password"]')
            .type('abcdefgh')
    })
    it('can show error message for the Terms of Service box', ()=>{
        cy.get('input[name="term"]')
            .check()
            .should('have.checked')
            .uncheck()
            .should('not.have.checked')
        cy.contains('Please read and accept')
            .should('exist')
        cy.get('input[name="term"]')
            .check()
        cy.get('button[name="submit"]')
            .click()
    })      
})